app/urls.py

from django.urls import path

from app import views


urlpatterns = [
    path('index/', views.index, name='index'),
    path('about/', views.about, name='index'),
    path('info/<int:id>', views.info, name ='info'),
    path('list/', views.list, name='list'),
    path('my_list/<int:id>/', views.my_list, name='my_list'),
    path('all_photoes/', views.all_photoes, name='all_photoes'),
    path('person_photoes/<int:id>/', views.person_photoes, name='person_photoes'),
    path('search/', views.search, name='search'),
    path('message/', views.message, name='message'),
]

blogback/urls.py
from django.contrib import admin

from django.urls import path, include, re_path
from django.contrib.staticfiles.urls import static

from app import views
from blogback.settings import MEDIA_URL, MEDIA_ROOT
from utils.upload_images import upload_image

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/', include(('app.urls', 'app'), namespace='app')),
    path('user/', include(('user.urls', 'user'), namespace='user')),
    path('article/', include(('article.urls', 'article'), namespace='article')),
    # kindeditor编辑器上传图片地址
    re_path(r'^util/upload/(?P<dir_name>[^/]+)$', upload_image, name='upload_image'),
    path('', views.index),
    path('photo/', include(('photo.urls', 'photo'), namespace='photo')),
    path('message/', include(('message.urls', 'message'), namespace='message')),
]

# 配置media访问路径
urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)


article/models.py
from django.db import models


class FatherTechnology(models.Model):
    f_name = models.CharField(max_length=20, null=True)
    f_alias = models.CharField(max_length=20)
    f_desc = models.CharField(max_length=20)
    class Meta:
        db_table = 'father_technology'

class ChildTechnology(models.Model):
    c_name = models.CharField(max_length=20)
    c_alias = models.CharField(max_length=20)
    f = models.ForeignKey(FatherTechnology, on_delete=models.CASCADE)
    c_desc = models.CharField(max_length=20)
    class Meta:
        db_table = 'child_technology'
class Article(models.Model):
    title = models.CharField(max_length=10, verbose_name='标题')
    content = models.TextField()
    desc = models.CharField(max_length=20, verbose_name='标题')
    s_time = models.DateTimeField(auto_now_add=True)
    child = models.ForeignKey(ChildTechnology, on_delete=models.CASCADE)
    father = models.ForeignKey(FatherTechnology, on_delete=models.CASCADE)
    icon = models.ImageField(upload_to='upload', null=True)
    class Meta:
        db_table = 'article'

templates/web/about.html

{% extends 'web/base_main.html' %}

{% block title %}
  周海龙
{% endblock %}

{% block extcss %}
  {% load static %}
  <link href="{% static 'web/css/base.css' %}" rel="stylesheet">
  <link href="{% static 'web/css/index.css' %}" rel="stylesheet">
  <link href="{% static 'web/css/m.css' %}" rel="stylesheet">
{% endblock %}

{% block extjs %}
     {% load static %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'web/js/comm.js' %}"></script>
    <script src="{% static 'web/js/modernizr.js' %}"></script>
    <script type="text/javascript" src="{% static 'web/js/hc-sticky.js' %}"></script>

    <script>


    </script>
{% endblock %}



{% block aboutme %}
<div class="about_me">
    <h2>关于我</h2>
    <ul>
        <i style="width:50%; height:50%;"><img src="/static/web/images/1.jpg"></i>
        <p><b>周海龙</b>，一个在在校大学生,为了生活,不得不去让自己努力,通过这个博客开始记录自己的点点滴滴</p>
    </ul>
</div>
{% endblock %}


{% block main %}

  <main class="r_box">
      <input type="hidden" value="about" id="title_id">
     <div class="about">
        <p>&emsp;我来自德阳，我是一名信息工程大学网络工程专业应届本科即将毕业的学员。</p>
        <p>&emsp;我的性格偏于内向，为人坦率、热情、讲求原则；处事乐观、专心、细致、头脑清醒；富有责任心、乐于助人。
我还是一个正直忠诚、勤奋求实的人，会不断追求人格的自我完善；明显的特点是乐观自信、温和开朗、稳重宽厚，因此，我人际关系和谐，适应环境能力较强。爱好电脑、科普知识，喜欢钻研，正因为这些增强了我的实干精神，习惯事情或问题及早解决。
最大的满足感在于该做的事顺利完成，以便有精力去关注其他，也就是追求感觉上的自我良好或优越感。最大的缺点是对没有秩序感的人可能缺乏足够的耐心，也可能因为心太细，会让别人误解我的一番好意。
        </p>
         <p><img src="/static/images/1.jpg" alt=""></p>
         <p>不知不觉的又是一个毕业季,时间飞快的流逝,恍惚还记得自己小时候的模样,回过头来才发现自己已经长大了,
         过了哪个只管向父母伸手的年龄了,自己也变成了一个需要上班养活的一类人了,犹记小时候期盼自己快点长大,但是
         真正长大才发现,生活好难</p>
         <p><img src="/static/images/12.jpg" alt=""></p>
         <p>知道开始做毕业设计的这一刻,发现自己需要真正意义上的独立,愿自己被这个世界温柔以待</p>
     </div>
  </main>

{% endblock %}

templates/web/all_photoes.html
{% extends 'web/base_main.html' %}

{% block title %}
相册
{% endblock %}

{% block extcss %}
<link rel="stylesheet" href="/static/web/css/base.css">
<link rel="stylesheet" href="/static/web/css/index.css">
<link rel="stylesheet" href="/static/web/css/info.css">
<link rel="stylesheet" href="/static/web/css/infopic.css">
<link rel="stylesheet" href="/static/web/css/m.css">
{% endblock %}

{% block content %}

<article>
  <div class="picbox">
        {% for photo in photoes %}
      <ul>
       <li data-scroll-reveal="enter bottom over 1s" ><i>{{ photo | safe }}</i></li>
    </ul>
      {% endfor %}
  </div>

  <div class="pagelist">
      {% for i in nums %}
      <a href="{% url 'app:person_photoes' id %}?page={{ i }}" class="curPage">{{ i }} </a>
    {% endfor %}
     <a href="{% url 'app:all_photoes' %}" class="curPage">返回 </a>
  </div>
</article>
{% endblock %}

{% block extjs %}
<script src="/static/web/js/jquery.min.js" type="text/javascript"></script>
<script type="text/javascript" src="/static/web/js/comm.js"></script>
<script src="/static/web/js/scrollReveal.js"></script>
<script>
	if (!(/msie [6|7|8|9]/i.test(navigator.userAgent))){
		(function(){
			window.scrollReveal = new scrollReveal({reset: true});
		})();
	};
</script>
{% endblock %}

templates/web/all_photoes2.html
{% extends 'web/base_main.html' %}

{% block title %}
相册
{% endblock %}

{% block extcss %}
<link rel="stylesheet" href="/static/web/css/base.css">
<link rel="stylesheet" href="/static/web/css/index.css">
<link rel="stylesheet" href="/static/web/css/info.css">
<link rel="stylesheet" href="/static/web/css/infopic.css">
<link rel="stylesheet" href="/static/web/css/m.css">
{% endblock %}

{% block content %}

<article>
  <div class="pagelist">
      {% for i in nums %}
      <a href="{% url 'app:'app:person_photoes' {{ id }} %}?page={{ i }}" class="curPage">{{ i }} </a>
    {% endfor %}
  </div>
</article>
{% endblock %}

{% block extjs %}
<script src="/static/web/js/jquery.min.js" type="text/javascript"></script>
<script type="text/javascript" src="/static/web/js/comm.js"></script>
<script src="/static/web/js/scrollReveal.js"></script>
<script>
	if (!(/msie [6|7|8|9]/i.test(navigator.userAgent))){
		(function(){
			window.scrollReveal = new scrollReveal({reset: true});
		})();
	};
</script>
{% endblock %}

templates/web/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>
        {% block title %}
        {% endblock %}
    </title>
    {% block extcss %}
    {% endblock %}

</head>
<body>
{% block header %}
{% endblock %}

{% block content %}
{% endblock %}

{% block footer %}
{% endblock %}

{% block extjs %}
{% endblock %}

</body>
</html>

templates/web/base_main.html

{% extends 'web/base.html' %}

{% block header %}
  <header class="header-navigation" id="header">
    <nav><div class="logo"><a href="/">周海龙个人博客</a></div>
      <h2 id="mnavh"><span class="navicon"></span></h2>
      <ul id="starlist">
        <li><a href="/app/index/">网站首页</a></li>
        <li><a href="/app/all_photoes/">我的相册</a></li>
        <li><a href="/app/list/">我的日记</a></li>
        <li><a href="/app/message/">留言</a></li>
        <li><a href="/app/about/">关于我</a></li>
      </ul>
  </nav>
  </header>
{% endblock %}

{% block extjs %}
    {% load static %}
    <script src="{% static 'web/js/jquery.min.js' %}" type="text/javascript"></script>
{% endblock %}

{% block content %}
  <article>
    <aside class="l_box">
        {% block aboutme %}

        {% endblock %}
        <div class="search">
          <form action="/app/search/" method="get">
            <input name="search_params" id="keyboard" class="input_text" value="请输入关键字词" style="color: rgb(153, 153, 153);" onfocus="if(value=='请输入关键字词'){this.style.color='#000';value=''}" onblur="if(value==''){this.style.color='#999';value='请输入关键字词'}" type="text">
            <input class="input_submit" value="搜索" type="submit">
          </form>
        </div>
        {% if photoes %}
            <div class="wdxc">
            <h2>我的相册</h2>
            <ul>
                {% for photo in photoes %}
              <li><a href="">{{ photo | safe }}</a></li>
                {% endfor %}
            </ul>
            </div>
        {% endif %}
        <div class="fenlei">
            <h2>文章分类</h2>
            <ul class="types_class">
            {% for article in articles %}
                <p><a href="{% url 'app:my_list' article.id %}">{{ article.c_name }}({{article.article_set.count}})</a></p>
            {% endfor %}
                <a href="/app/list/">所有文章</a>
            </ul>
        </div>
        <div class="tuijian">
          <h2>站长推荐</h2>
          <ul class="tuijian_class">
            {% for article in articles1 %}
              <p><a href="{% url 'app:info' article.id %}">{{ article.title }}</a></p>
            {% endfor %}
          </ul>
        </div>
    </aside>
      {% block main %}


      {% endblock %}
  </article>

{% endblock %}

{% block footer %}
  <footer>
    <a href="" target="_blank">周海龙个人博客</a>
  </footer>
  <a href="#" class="cd-top">Top</a>
{% endblock %}

templates/web/gbook.html
{% extends 'web/base_main.html' %}


{% block title %}
留言
{% endblock %}

{% block extcss %}
<link href="/static/web/css/base.css" rel="stylesheet">
<link href="/static/web/css/index.css" rel="stylesheet">
<link href="/static/web/css/m.css" rel="stylesheet">
{% endblock %}

{% block extjs %}
{{ block.super }}
<script src="/static/web/js/jquery.min.js" type="text/javascript"></script>
<script type="text/javascript" src="/static/web/js/hc-sticky.js"></script>
<script type="text/javascript" src="/static/web/js/comm.js"></script>
<!--[if lt IE 9]>
<script src="/static/web/js/modernizr.js"></script>
<![endif]-->
{% endblock %}

{% block aboutme %}
<div class="about_me">
    <h2>关于我</h2>
    <ul>
        <i style="width:50%; height:50%;"><img src="/static/web/images/1.jpg"></i>
        <p><b>周海龙</b>，一个在在校大学生,为了生活,不得不去让自己努力,通过这个博客开始记录自己的点点滴滴</p>
    </ul>
</div>
{% endblock %}

{% block main %}
  <main class="r_box">
<div class="gbook">

    {% for message in messages %}
      <div class="fb">
        <ul>
          <p class="fbtime"><span>{{message.time | safe }}</span> {{ message.name }}</p>
          <p class="fbinfo">{{ message.content | safe }}</p>
        </ul>
      </div>
      <div class="hf">
          {% if message.answer %}
            <ul>
              <p class="zzhf"><font color="#FF0000">站长回复:</font>{{ message.answer | safe }}</p>
            </ul>
          {% else %}
            <ul>
              <p class="zzhf"><font>没有回复</p>
            </ul>
          {% endif %}
      </div>
    {% endfor %}

      <div class="gbox">
        <form action="" method="post" name="form1" id="form1">
          {% csrf_token %}
          <p> <strong>来说点儿什么吧...</strong></p>
          <p><span> 您的姓名:</span>
            <input name="name" type="text" id="name">
            *</p>
          <p><span>联系邮箱:</span>
            <input name="email" type="text" id="email">
            *</p>
          <p><span class="tnr">留言内容:</span>
            <textarea name="lytext" cols="60" rows="12" id="lytext"></textarea>
          </p>
          <p>
            <input type="submit" name="Submit3" value="提交">
            <input name="enews" type="hidden" id="enews" value="AddGbook">
          </p>
        </form>
      </div>
    </div>
  </main>
{% endblock %}

templates/web/index.html

{% extends 'web/base_main.html' %}

{% block title %}
  周海龙个人博客
{% endblock %}

{% block extcss %}
  {% load static %}
  <link href="{% static 'web/css/base.css' %}" rel="stylesheet">
  <link href="{% static 'web/css/index.css' %}" rel="stylesheet">
  <link href="{% static 'web/css/m.css' %}" rel="stylesheet">
{% endblock %}

{% block extjs %}
  {% load static %}
    {{ block.super }}
  <script type="text/javascript" src="{% static 'web/js/comm.js' %}"></script>
  <script src="{% static 'web/js/modernizr.js' %}"></script>
{% endblock %}


{% block aboutme %}
<div class="about_me">
    <h2>关于我</h2>
    <ul>
        <i style="width:50%; height:50%;"><img src="/static/web/images/1.jpg"></i>
        <p><b>周海龙</b>，一个在在校大学生,为了生活,不得不去让自己努力,通过这个博客开始记录自己的点点滴滴</p>
    </ul>
</div>
{% endblock %}


{% block main %}
    <main class="r_box">
        {% for article in articles1 %}
            <li>
                 <img style="width:200px; height:100px" src="/media/{{ article.icon }}" alt="">
                <h3>标题:<a href="{% url 'app:info' article.id %}">{{ article.title }}</a></h3>
                文章描述:{{ article.desc }}
            </li>
        {% endfor %}
    </main>

{% endblock %}



templates/web/info.html

{% extends 'web/base_main.html' %}

{% block title %}
  周海龙
{% endblock %}

{% block extcss %}
  {% load static %}
  <link href="{% static 'web/css/base.css' %}" rel="stylesheet">
  <link href="{% static 'web/css/index.css' %}" rel="stylesheet">
  <link href="{% static 'web/css/m.css' %}" rel="stylesheet">
{% endblock %}

{% block extjs %}
  {% load static %}
    {{ block.super }}
  <script type="text/javascript" src="{% static 'web/js/comm.js' %}"></script>
  <script src="{% static 'web/js/modernizr.js' %}"></script>
{% endblock %}


{% block main %}

    <main>
        <div class="infosbox">
            <div class="newsview">
                <h3 class="news_title">{{ article.title }}</h3>
                <div class="bloginfo">
                    <ul>
                        <li class="author">作者：<a href="/">周海龙</a></li>
                        <li class="timer">时间：{{ article.s_time }}</li>
                        <!--<li class="view">4567人已阅读</li>-->
                    </ul>
                </div>
                <div class="tags">
                    <a href="/" target="_blank">个人博客</a> &nbsp;
                    <a href="/" target="_blank">{{ cate.c_name }}</a>
                </div>
                <div class="news_about">
                   {{ article.content|safe }}
                </div>
            </div>
            <br>
            <br>
            <br>
                {% for ca in cate1 %}
                    <div class="news_about">
                    {% if ca.id > id %}
                        <a href="{% url 'app:info' ca.id %}">下一篇&emsp;{{ ca.title }}</a>
                    {% endif %}

                    {% if ca.id < id %}
                        <a href="{% url 'app:info' ca.id %}">上一篇&emsp;{{ ca.title }}</a>
                    {% endif %}
                    </div>
                {% endfor %}
        </div>
    </main>

{% endblock %}

templates/web/list.html

{% extends 'web/base_main.html' %}

{% block title %}
  周海龙
{% endblock %}

{% block extcss %}
  {% load static %}
  <link href="{% static 'web/css/base.css' %}" rel="stylesheet">
  <link href="{% static 'web/css/index.css' %}" rel="stylesheet">
  <link href="{% static 'web/css/m.css' %}" rel="stylesheet">
{% endblock %}

{% block extjs %}
     {% load static %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'web/js/comm.js' %}"></script>
    <script src="{% static 'web/js/modernizr.js' %}"></script>
    <script type="text/javascript" src="{% static 'web/js/hc-sticky.js' %}"></script>
{% endblock %}


{% block main %}

    <main class="r_box">
        {% for article in all_article %}
                <li>
                    <img style="width:200px; height:100px" src="/media/{{ article.icon }}" alt="">
                    <h3><a href="{% url 'app:info' article.id %}">{{ article.title }}</a></h3>
                    <p>{{ article.desc }}</p>
                </li>
        {% endfor %}


        {% for article in articles2 %}
            <li>
                <img style="width:200px; height:100px" src="/media/{{ article.icon }}" alt="">
                <h3><a href="{% url 'app:info' article.id %}">{{ article.title }}</a></h3>
                <p>{{ article.desc }}</p>
            </li>
        {% endfor %}

        {% if articles2.has_previous %}
            <a href="{% url 'app:list' %}?page={{ articles2.previous_page_number }}">上一页</a>
        {% endif %}

        {% for i in articles2.paginator.page_range%}
        <a href="{% url 'app:list' %}?page={{ i }}">{{ i }}</a>
        {% endfor %}

        {% if articles2.has_next %}
            <a href="{% url 'app:list' %}?page={{ articles2.next_page_number }}">下一页</a>
        {% endif %}
    </main>

{% endblock %}

templates/web/search.html

{% extends 'web/base_main.html' %}

{% block title %}
  周海龙个人博客网站
{% endblock %}

{% block extcss %}
  {% load static %}
  <link href="{% static 'web/css/base.css' %}" rel="stylesheet">
  <link href="{% static 'web/css/index.css' %}" rel="stylesheet">
  <link href="{% static 'web/css/m.css' %}" rel="stylesheet">
{% endblock %}

{% block extjs %}
     {% load static %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'web/js/comm.js' %}"></script>
    <script src="{% static 'web/js/modernizr.js' %}"></script>
    <script type="text/javascript" src="{% static 'web/js/hc-sticky.js' %}"></script>
{% endblock %}


{% block main %}

    <main class="r_box">
        {% for article in articles1 %}
            <li>
                <h3><a href="{% url 'app:info' article.id %}">{{ article.title }}</a></h3>
                <p>{{ article.desc }}</p>
            </li>
        {% endfor %}
        {% if articles1 %}
            <div class="pagelist">
                <a class="allpage"><b>共{{ articles1.paginator.num_pages }}条</b></a>&nbsp;&nbsp;

                {% if articles1.has_previous %}
                    <a href="{% url 'blog:list' %}?page={{ articles.previous_page_number }}&search_params={{ search_params }}">上一页</a>
                {% endif %}

                {% for i in articles1.paginator.page_range %}
                    {% if articles1.number == i %}
                        <a href="{% url 'blog:list' %}?page={{ i }}&search_params={{ search_params }}"  class="curPage">{{ i }}</a>&nbsp;&nbsp;
                    {% else%}
                        <a href="{% url 'blog:list' %}?page={{ i }}&search_params={{ search_params }}">{{ i }}</a>&nbsp;&nbsp;
                    {% endif %}

                {% endfor %}

                {% if articles1.has_next %}
                    <a href="{% url 'blog:list' %}?page={{ articles.next_page_number }}&search_params={{ search_params }}">下一页</a>
                {% endif %}
            </div>
        {% else %}
            <p>还没发布文章呢</p>
        {% endif %}
    </main>

{% endblock %}

templates/web/share.html
{% extends 'web/base_main.html' %}

{% block title %}
相册
{% endblock %}

{% block extcss %}
<link rel="stylesheet" href="/static/web/css/base.css">
<link rel="stylesheet" href="/static/web/css/index.css">
<link rel="stylesheet" href="/static/web/css/info.css">
<link rel="stylesheet" href="/static/web/css/infopic.css">
<link rel="stylesheet" href="/static/web/css/m.css">
{% endblock %}

{% block content %}

<article>
  <div class="picbox">
        {% for photo in photoes %}
      <ul>
       <li data-scroll-reveal="enter bottom over 1s" ><a href="{% url 'app:person_photoes' photo.3 %}"><i>{{ photo.0 | safe }}</i>
        <div class="picinfo">
          <h3>{{ photo.1 }}</h3>
          <span>{{ photo.2 }}</span> </div>
        </a></li>
    </ul>
      {% endfor %}
  </div>
  <div class="pagelist">&nbsp;<a href="#" class="curPage">1</a></div>
</article>
{% endblock %}

{% block extjs %}
<script src="/static/web/js/jquery.min.js" type="text/javascript"></script>
<script type="text/javascript" src="/static/web/js/comm.js"></script>
<script src="/static/web/js/scrollReveal.js"></script>
<script>
	if (!(/msie [6|7|8|9]/i.test(navigator.userAgent))){
		(function(){
			window.scrollReveal = new scrollReveal({reset: true});
		})();
	};
</script>
{% endblock %}