app/urls.py

from django.urls import path

from app import views


urlpatterns = [
    path('index/', views.index, name='index'),
    path('about/', views.about, name='index'),
    path('info/<int:id>', views.info, name ='info'),
    path('list/', views.list, name='list'),
    path('my_list/<int:id>/', views.my_list, name='my_list'),
    path('all_photoes/', views.all_photoes, name='all_photoes'),
    path('person_photoes/<int:id>/', views.person_photoes, name='person_photoes'),
    path('search/', views.search, name='search'),
    path('message/', views.message, name='message'),
]

article/urls.py
from django.urls import path

from article import views

urlpatterns = [
    #编辑文章
    path(r'edit_article/', views.edit_article, name='edit_article'),
    #获取文章
    path(r'article/', views.article, name='article'),
    #添加栏目
    path('category/', views.category, name='category'),
    #显示栏目
    path('all_category/', views.all_category, name='all_category'),
    # 修改栏目
    path('up_category/<int:id>/', views.up_category, name='up_category'),
    #添加文章
    path('all_edit/', views.all_edit, name='all_edit'),
    #删除文章
    path('del_article/<int:id>', views.del_article, name='del_article'),
    path('up_article/<int:id>', views.up_article, name='up_article'),
    #删除栏目
    path('del_category/<int:id>', views.del_category, name='del_category'),
    #测试
    path('look/', views.look, name='look'),
]

blogback/urls.py
from django.contrib import admin

from django.urls import path, include, re_path
from django.contrib.staticfiles.urls import static

from app import views
from blogback.settings import MEDIA_URL, MEDIA_ROOT
from utils.upload_images import upload_image

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/', include(('app.urls', 'app'), namespace='app')),
    path('user/', include(('user.urls', 'user'), namespace='user')),
    path('article/', include(('article.urls', 'article'), namespace='article')),
    # kindeditor编辑器上传图片地址
    re_path(r'^util/upload/(?P<dir_name>[^/]+)$', upload_image, name='upload_image'),
    path('', views.index),
    path('photo/', include(('photo.urls', 'photo'), namespace='photo')),
    path('message/', include(('message.urls', 'message'), namespace='message')),
]

# 配置media访问路径
urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)


message/urls.py
from django.urls import path

from message import views

urlpatterns = [
    path('message/', views.message, name='message'),
    path('answer/<int:id>/', views.answer, name='answer'),
    path('del_message/<int:id>/', views.del_message, name='del_message')
]

photo/urls.py
from django.urls import path
from photo import views

urlpatterns = [
    path('photoes/', views.photoes, name='photoes'),
    path('add_photoes/', views.add_photoes, name='add_photoes'),
    path('del_photoes/<int:id>/', views.del_photoes, name='del_photoes'),
    path('up_photoes/<int:id>/', views.up_photoes, name='up_photoes'),
    path('my_file/', views.my_file, name='my_file'),
    path('del_my_file/<int:id>/', views.del_my_file, name='del_my_file'),
    path('test/', views.test, name='test')
]

user/urls.py
from django.urls import path

from user import views

urlpatterns = [
    path('login/', views.login, name='login'),
    path('index/', views.index, name='index'),
    path('logout/', views.logout, name='logout'),
    path('all_index/', views.all_index, name='all_index'),
    path('manage_user/', views.manage_user, name='manage_user'),
    path('update_user/', views.update_user, name='update_user'),
    path('del_user/<int:id>', views.del_user, name='del_user')

]


article/models.py
from django.db import models


class FatherTechnology(models.Model):
    f_name = models.CharField(max_length=20, null=True)
    f_alias = models.CharField(max_length=20)
    f_desc = models.CharField(max_length=20)
    class Meta:
        db_table = 'father_technology'

class ChildTechnology(models.Model):
    c_name = models.CharField(max_length=20)
    c_alias = models.CharField(max_length=20)
    f = models.ForeignKey(FatherTechnology, on_delete=models.CASCADE)
    c_desc = models.CharField(max_length=20)
    class Meta:
        db_table = 'child_technology'
class Article(models.Model):
    title = models.CharField(max_length=10, verbose_name='标题')
    content = models.TextField()
    desc = models.CharField(max_length=20, verbose_name='标题')
    s_time = models.DateTimeField(auto_now_add=True)
    child = models.ForeignKey(ChildTechnology, on_delete=models.CASCADE)
    father = models.ForeignKey(FatherTechnology, on_delete=models.CASCADE)
    icon = models.ImageField(upload_to='upload', null=True)
    class Meta:
        db_table = 'article'

message/models.py
from django.db import models

# Create your models here.

article/views.py
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.shortcuts import render

# Create your views here.
from django.urls import reverse

from app.models import Message
from article.models import Article, FatherTechnology, ChildTechnology


# def test(request):
#     if request.method == 'GET':
#         return render(request, 'test.html')
#     if request.method == 'POST':
#         return HttpResponseRedirect(reverse('edit.html'))


# 编辑文章
def edit_article(request):
    """
    文章编辑方法
    """
    if request.method == 'GET':
        return all_edit(request)
    if request.method == 'POST':
        # 获取文章的标题和内容
        title = request.POST.get('title')
        content = request.POST.get('content')
        desc = request.POST.get('describe')
        category = request.POST.get('category')
        icon = request.FILES.get('titlepic')
        # 使用all()方法进行判断，如果文章标题和内容任何一个参数没有填写，则返回错误信息
        child = ChildTechnology.objects.filter(id=category).first()

        Article.objects.create(title=title,
                               content=content,
                               desc=desc,
                               child_id=child.id,
                               father_id=child.f_id,
                               icon=icon)
        # 创建文章成功后，跳转到文章列表页面
        return HttpResponseRedirect(reverse('user:index'))


# 显示所有文章
def article(request):
    if request.method == 'GET':
        # 获取所有的文章
        articles = Article.objects.all()
        return render(request, 'article.html', {'articles': articles})


# 获取栏目
def category(request):
    if request.method == 'GET':
        return all_category(request)
    if request.method == 'POST':
        name = request.POST.get('name')
        alias = request.POST.get('alias')
        fid = request.POST.get('sel')
        describe = request.POST.get('describe')
        if fid == '0':
            FatherTechnology.objects.create(f_name=name,
                                            f_alias=alias,
                                            f_desc=describe)
            return HttpResponseRedirect(reverse('article:category'))
        elif fid == '1':
            f_id = FatherTechnology.objects.filter(id=fid).first()
            ChildTechnology.objects.create(c_name=name,
                                           c_alias=alias,
                                           c_desc=describe,
                                           f_id=f_id.id)
            return HttpResponseRedirect(reverse('article:category'))
        elif fid == '2':
            f_id = FatherTechnology.objects.filter(id=fid).first()
            ChildTechnology.objects.create(c_name=name,
                                           c_alias=alias,
                                           c_desc=describe,
                                           f_id=f_id.id)
            return HttpResponseRedirect(reverse('article:category'))
        elif fid == '3':
            f_id = FatherTechnology.objects.filter(id=fid).first()
            ChildTechnology.objects.create(c_name=name,
                                           c_alias=alias,
                                           c_desc=describe,
                                           f_id=f_id.id)

            return HttpResponseRedirect(reverse('article:category'))

        elif fid == '4':
            f_id = FatherTechnology.objects.filter(id=fid).first()
            ChildTechnology.objects.create(c_name=name,
                                           c_alias=alias,
                                           c_desc=describe,
                                           f_id=f_id.id)

            return HttpResponseRedirect(reverse('article:category'))

# 显示所有栏目
def all_category(request):
    all_data = FatherTechnology.objects.all()
    mess = Message.objects.filter(answer__isnull=True)
    mess1 = len(mess)
    return render(request, 'category.html', {'all_data': all_data, 'mess1': mess1})


# 显示所有子栏目
def all_edit(request):
    all_data = ChildTechnology.objects.all()
    mess = Message.objects.filter(answer__isnull=True)
    mess1 = len(mess)
    return render(request, 'add-article.html', {'all_data': all_data, 'mess1': mess1})

# 删除文章
def del_article(request, id):
        Article.objects.filter(pk=id).delete()
        return HttpResponseRedirect(reverse('user:index'))


# 修改文章
def up_article(request, id):
    if request.method == 'GET':
        user = Article.objects.filter(pk=id).first()
        return render(request, 'update-article.html', {'user': user})
    if request.method == 'POST':
        user = Article.objects.filter(pk=id).first()
        title = request.POST.get('title')
        content = request.POST.get('content')
        describe = request.POST.get('describe')
        user.title = title
        user.content = content
        user.desc = describe
        user.save()
        return HttpResponseRedirect(reverse('user:index'))


# def up_article(request, id):
#     if request.method == 'GET':
#         return render(request, 'update.html')
#     if request.method == 'POST':
#         title = request.POST.get('title')
#         Article.objects.filter(id=id).update(title=title)
#         return HttpResponseRedirect(reverse('user:index'))


# 删除栏目
def del_category(request, id):
    FatherTechnology.objects.filter(pk=id).delete()
    return HttpResponseRedirect(reverse('article:category'))


#修改栏目
def up_category(request, id):
    if request.method == 'GET':
        categorys = FatherTechnology.objects.filter(pk=id).first()
        all_data = FatherTechnology.objects.all()
        mess = Message.objects.filter(answer__isnull=True)
        mess1 = len(mess)
        return render(request, 'update-category.html', {'categorys': categorys, 'all_data': all_data, 'mess1': mess1})

    if request.method == 'POST':
        name = request.POST.get('name')
        alias = request.POST.get('alias')
        fid = request.POST.get('sel')
        describe = request.POST.get('describe')
        category = FatherTechnology.objects.filter(pk=id).first()
        category.f_name = name
        category.f_alias = alias
        category.f_desc = describe
        category.save()
        return HttpResponseRedirect(reverse('article:category'))

# 测试
def look(request):
    all_data2 = Article.objects.all()
    return render(request, 'test.html', {'all_data2':all_data2})


message/views.py
from django.shortcuts import render

from django.http import HttpResponseRedirect
# Create your views here.
from django.urls import reverse

from app.models import Message


# 收到的信息
def message(request):
    if request.method == 'GET':
        # 查询数据库answer字段是否为空
        mess = Message.objects.filter(answer__isnull=True)
        mess1 = len(mess)
        # 返回数据
        message = Message.objects.all()
        return render(request, 'message.html', {'message': message, 'mess1': mess1})


# 回复
def answer(request, id):
    if request.method == 'GET':
        message = Message.objects.filter(id=id).first()
        mess = Message.objects.filter(answer__isnull=True)
        mess1 = len(mess)
        return render(request, 'answer.html', {'message': message, 'mess1': mess1})
    if request.method == 'POST':
        answer = request.POST.get('answer')
        message = Message.objects.filter(id=id).first()
        message.answer = answer
        message.save()
        return HttpResponseRedirect(reverse('message:message'))


# 删除回复
def del_message(request, id):
    Message.objects.filter(id=id).delete()
    return HttpResponseRedirect(reverse('message:message'))




templates/add-category.html
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>无标题文档</title>
</head>

<body>
</body>
</html>

templates/answer.html
{% extends 'base_admin.html' %}

{% block title %}
添加图片
{% endblock %}

{% block js %}
{{ block.super }}
  <link rel="apple-touch-icon-precomposed" href="images/icon/icon.png">
  <link rel="shortcut icon" href="images/icon/favicon.ico">
{% endblock %}


{% block content %}
<section class="container-fluid">

  <div class="row">

    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-lg-10 col-md-offset-2 main" id="main">
      <div class="row">
        <form action="" method="post" class="add-article-form" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="col-md-9">
            <h1 class="page-header">撰写新公告</h1>
            <div class="form-group">
              <label for="article-title" class="sr-only">标题</label>
              <input type="text" id="article-title" name="name" value="{{ message.name }}" class="form-control" required autofocus autocomplete="off">
              <br/>
              <input type="text"  name="name" value="{{ message.email }}" class="form-control" required autofocus autocomplete="off">
            </div>
            <div class="form-group">
              <label for="article-content" class="sr-only">内容</label>
                内容：<textarea id="editor_id" class="form-control" name="content"  style="width: 925px; height: 200px">
                {{ message.content | safe }}
            </textarea>
            </div>
            <div class="add-article-box">
              <h2 class="add-article-box-title"><span>回复</span></h2>
              <div class="add-article-box-content">
              	<textarea class="form-control" name="answer" autocomplete="off">
                    {{ message.answer }}
                </textarea>
                <span class="prompt-text">描述是可选的手工创建的内容总结，并可以在网页描述中使用</span>
              </div>
            </div>
          </div>
          <div class="col-md-3">
            <h1 class="page-header">操作</h1>
            <div class="add-article-box">
              <h2 class="add-article-box-title"><span>发布</span></h2>
              <div class="add-article-box-content">
              	<p><label>状态：</label><span class="article-status-display">未发布</span></p>
                <p><label>公开度：</label><input type="radio" name="visibility" value="0" checked/>公开 <input type="radio" name="visibility" value="1" />加密</p>
                <p><label>发布于：</label><span class="article-time-display"><input style="border: none;" type="datetime" name="time" value="2016-01-09 17:29:37" /></span></p>
              </div>
              <div class="add-article-box-footer">
                <button class="btn btn-primary" type="submit" name="submit">回复</button>
              </div>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</section>
{% endblock %}

templates/category.html
{% extends 'base_admin.html' %}

{% block title %}
栏目
{% endblock %}
{% block js %}
{{ block.super }}
<script src="/static/js/bootstrap.min.js"></script>
<script src="/static/js/admin-scripts.js"></script>
<script>
//是否确认删除
$(function(){
	$("#main table tbody tr td a").click(function(){
		var name = $(this);
		var id = name.attr("rel"); //对应id
		if (event.srcElement.outerText === "删除")
		{
			if(window.confirm("此操作不可逆，是否确认？"))
			{
				$.ajax({
					type: "POST",
					url: "/Category/delete",
					data: "id=" + id,
					cache: false, //不缓存此页面
					success: function (data) {
						window.location.reload();
					}
				});
			};
		};
	});
});
</script>
{% endblock %}
{% block content %}
<section class="container-fluid">
  <div class="row">
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-lg-10 col-md-offset-2 main" id="main">
      <div class="row">
        <div class="col-md-5">
          <h1 class="page-header">添加</h1>
          <form action="" method="post">
              {% csrf_token %}
            <div class="form-group">
              <label for="category-name">栏目名称</label>
              <input type="text" id="category-name" name="name" class="form-control" placeholder="在此处输入栏目名称" required autocomplete="off">
            <div class="form-group">
              <label for="category-alias">栏目别名</label>
              <input type="text" id="category-alias" name="alias" class="form-control" placeholder="在此处输入栏目别名" required autocomplete="off">
              <span class="prompt-text">“别名”是在URL中使用的别称，它可以令URL更美观。通常使用小写，只能包含字母，数字和连字符（-）。</span> </div>
            <div class="form-group">
              <label for="category-fname">父节点</label>

              <select id="category-fname" class="form-control" name="sel">
                  <option value=0 selected>无</option>
                  {% for data in all_data %}
                  <option value="{{ data.id }}">{{ data.f_name }}</option>
                {% endfor %}
              </select>
              <span class="prompt-text">栏目是有层级关系的，您可以有一个“音乐”分类目录，在这个目录下可以有叫做“流行”和“古典”的子目录。</span> </div>
              <label for="category-describe">描述</label>
              <textarea class="form-control" id="category-describe" name="describe" rows="4" autocomplete="off"></textarea>
              <span class="prompt-text">描述会出现在网页的description属性中。</span> </div>
            <button class="btn btn-primary" type="submit" name="submit" style="margin-bottom:40px">添加新栏目</button>
          </form>
        </div>
        <div class="col-md-7">
          <h1 class="page-header">管理 <span class="badge">3</span></h1>
          <div class="table-responsive">
            <table class="table table-striped table-hover">
              <thead>
                <tr>
                  <th><span class="glyphicon glyphicon-paperclip"></span> <span class="visible-lg">ID</span></th>
                  <th><span class="glyphicon glyphicon-file"></span> <span class="visible-lg">名称</span></th>
                  <th><span class="glyphicon glyphicon-list-alt"></span> <span class="visible-lg">别名</span></th>
                  <th><span class="glyphicon glyphicon-pushpin"></span> <span class="visible-lg">总数</span></th>
                  <th><span class="glyphicon glyphicon-pencil"></span> <span class="visible-lg">操作</span></th>
                </tr>
              </thead>
              <tbody>
              {% for data in all_data %}
                <tr>
                  <td>{{data.id}}</td>
                  <td>{{ data.f_name }}</td>
                  <td>{{ data.f_alias }}</td>
                  <td> {{ data.childtechnology_set.all.count }} </td>
                  <td><a href="{% url 'article:up_category' data.id %}">修改</a> <a href="{% url 'article:del_category' data.id %}">删除</a></td>
                    <br>
                </tr>
              {% endfor %}
                <!--<tr>-->
                  <!--<td>2</td>-->
                  <!--<td>后端程序</td>-->
                  <!--<td>program</td>-->
                  <!--<td>185</td>-->
                  <!--<td><a href="update-category.html">修改</a> <a rel="2">删除</a></td>-->
                <!--</tr>-->
                <!--<tr>-->
                  <!--<td>3</td>-->
                  <!--<td>管理系统</td>-->
                  <!--<td>cms</td>-->
                  <!--<td>223</td>-->
                  <!--<td><a href="update-category.html">修改</a> <a rel="3">删除</a></td>-->
                <!--</tr>-->
              </tbody>
            </table>
            <span class="prompt-text"><strong>注：</strong>删除一个栏目也会删除栏目下的文章和子栏目,请谨慎删除!</span> </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}

templates/index.html

{% extends 'base_admin.html' %}

{% block title %}
首页
{% endblock %}

{% block content %}

<script>
  function article_update(id){
    var title = "#" + id + "_title";
    var category = "#" + id + "_category";
    var tag = "#" + id + "_tag";
    <!--var pinlun = "#" + id + "_pinlun";-->
    var operator = "#" + id  + "_operator";

    $(category).html('<input id=' + category + ' type="text" value=' + $(category).text() + '></input>');
    $(tag).html('<input id=' + tag + ' type="text" value=' + $(tag).text() + '></input>');
    <!--$(pinlun).html('<input id=' + pinlun + ' type="text" value=' + $(pinlun).text() + '></input>');-->
    $(title).html('<input id=' + title + ' type="text" value=' + $(title).text() + '></input>');
    operator_content = '<a onclick="up_article('+id+');">完成</a> <a href="/user/index/">取消</a>';
    $(operator).html(operator_content);
  }
  function up_article(id){
          var a_title =  $("#" + id + "_title").val()
          var csrf = $('input[name="csrfmiddlewaretoken"]').val()
          console.log(a_title)
          console.log(id)
          $.ajax({
               url:'/article/up_article/',
               type: 'POST',
               data:{'article_id':id, 'article_title':a_title},
               headers:{'X-CSRFToken':csrf},
               dataType:'json',
               success:function(data){
                  if(data.code == '200'){
                      <!--$('#' + id + '_title').text(data.title)-->
                  }
               }
          })
  }

</script>
<section class="container-fluid">
  <div class="row">
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-lg-10 col-md-offset-2 main" id="main" style="position:absolute;">
      <form action="/Article/checkAll" method="post"  >
        <h1 class="page-header">操作</h1>
        <ol class="breadcrumb">
          <li><a href="/article/edit_article">增加文章</a></li>
        </ol>
        <h1 class="page-header">管理 <span class="badge">7</span></h1>
        <div class="table-responsive">
          <table class="table table-striped table-hover">
            <thead>
              <tr>
                <th><span class="glyphicon glyphicon-th-large"></span> <span class="visible-lg">选择</span></th>
                <th><span class="glyphicon glyphicon-file"></span> <span class="visible-lg">标题</span></th>
                <th><span class="glyphicon glyphicon-list"></span> <span class="visible-lg">栏目</span></th>
                <th class="hidden-sm"><span class="glyphicon glyphicon-tag"></span> <span class="visible-lg">标签</span></th>
                <th class="hidden-sm"><span class="glyphicon glyphicon-comment"></span> <span class="visible-lg">评论</span></th>
                <th><span class="glyphicon glyphicon-time"></span> <span class="visible-lg">日期</span></th>
                <th><span class="glyphicon glyphicon-pencil"></span> <span class="visible-lg">操作</span></th>
              </tr>
            </thead>
            <tbody>
              <!--{% csrf_token %}-->
              {% for data in all_data2 %}
              <tr>
                <td><input type="checkbox" class="input-control" name="checkbox[]" value="{{ data.id }}" /></td>
                <td id="{{ data.id }}_title" class="article-title">{{ data.title }}</td>
                <td id="{{ data.id }}_category">{{ data.father.f_name }}</td>
                <td id="{{ data.id }}_tag" class="hidden-sm ">{{ data.child.c_name }}</td>
                <td id="{{ data.id }}_pinlun" class="hidden-sm">{{ data.id }}</td>
                <td id="{{ data.id }}_time" class="zhl">{{ data.s_time }}</td>
                <td id="{{ data.id }}_operator"><a href="{% url 'article:up_article' data.id %}">修改</a> <a href="{% url 'article:del_article' data.id %}">删除</a></td>
              </tr>
              {% endfor %}


              <!--{% if orders.has_next %}-->
                  <!--<a href="{% url 'user:all_index' %}?page={{ orders.next_page_number }}">下一页></a>-->
              <!--{% endif %}-->
            </tbody>
          </table>
        </div>
        <footer class="message_footer">
          <nav>
            <div class="btn-toolbar operation" role="toolbar">
              <div class="btn-group" role="group"> <a class="btn btn-default" onClick="select()">全选</a> <a class="btn btn-default" onClick="reverse()">反选</a> <a class="btn btn-default" onClick="noselect()">不选</a> </div>
              <div class="btn-group" role="group">
                <button type="submit" class="btn btn-default" data-toggle="tooltip" data-placement="bottom" title="删除全部选中" name="checkbox_delete">删除</button>
              </div>
            </div>
            <ul class="pagination pagenav">
              <li>
              {% if all_data2.has_previous %}
                  <a href="{% url 'user:all_index' %}?page={{ all_data2.previous_page_number }}">上一页</a>
              {% endif %}
              </li>
              <li>
              {% for i in all_data2.paginator.page_range %}
              <a href="{% url 'user:all_index' %}?page={{ i }}">{{ i }}</a>
              {% endfor %}
              </li>
              <li>
              {% if all_data2.has_next %}
              <a href="{% url 'user:all_index' %}?page={{ all_data2.next_page_number }}">下一页</a>
              {% endif %}
              </li>
            </ul>
          </nav>
        </footer>
      </form>
    </div>
  </div>
</section>

{% endblock %}

templates/manage-user.html
{% extends 'base_admin.html' %}

{% block title %}
用户
{% endblock %}


{% block extcss %}
{{ block.super }}
<link rel="apple-touch-icon-precomposed" href="/static/images/icon/icon.png">
<link rel="shortcut icon" href="/static/images/icon/favicon.ico">
{% endblock %}

{% block content %}
<section class="container-fluid">

  <div class="row">

    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-lg-10 col-md-offset-2 main" id="main">
        <h1 class="page-header">管理 <span class="badge">2</span></h1>
        <div class="table-responsive">
          <table class="table table-striped table-hover">
            <thead>
              <tr>
                <th><span class="glyphicon glyphicon-th-large"></span> <span class="visible-lg">ID</span></th>
                <th><span class="glyphicon glyphicon-user"></span> <span class="visible-lg">用户名</span></th>
                <th><span class="glyphicon glyphicon-pushpin"></span> <span class="visible-lg">文章</span></th>
                <th><span class="glyphicon glyphicon-time"></span> <span class="visible-lg">创建时间</span></th>
                <th><span class="glyphicon glyphicon-pencil"></span> <span class="visible-lg">操作</span></th>
              </tr>
            </thead>
            <tbody>
              <tr>
                {% for user in users %}
                <td>{{ user.id }}</td>
                <td>{{ user.s_name }}</td>
                <td>{{ art }}</td>
                <td>{{ user.crate_time }}</td>
                <td><a href="/user/update_user/">修改</a> <a href="{% url 'user:del_user' user.id %}">删除</a>
                {% endfor %}
              </tr>
            </tbody>
          </table>
        </div>
    </div>
  </div>
</section>
{% endblock %}

templates/notice.html
{% extends 'base_admin.html' %}
{% block title %}
管理图片
{% endblock %}
{% block css %}
{{ block.super }}
  <link rel="apple-touch-icon-precomposed" href="images/icon/icon.png">
  <link rel="shortcut icon" href="images/icon/favicon.ico">
{% endblock %}

{% block content %}
<section class="container-fluid">
  <div class="row">
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-lg-10 col-md-offset-2 main" id="main">
      <form action="" method="post" >
        <h1 class="page-header">操作</h1>
        <ol class="breadcrumb">
          <li><a href="/photo/add_photoes/">增加相册</a></li>
        </ol>
        <h1 class="page-header">管理 <span class="badge">3</span></h1>
        <div class="table-responsive">
          <table class="table table-striped table-hover">
            <thead>
              <tr>
                <th><span class="glyphicon glyphicon-th-large"></span> <span class="visible-lg">选择</span></th>
                <th><span class="glyphicon glyphicon-file"></span> <span class="visible-lg">标题</span></th>
                <th><span class="glyphicon glyphicon-time"></span> <span class="visible-lg">日期</span></th>
                <th><span class="glyphicon glyphicon-pencil"></span> <span class="visible-lg">操作</span></th>
              </tr>
            </thead>
            <tbody>
            {% for photo in photoes %}
              <tr>
                <td><input type="checkbox" class="input-control" name="checkbox[]" value="" /></td>
                <td class="article-title">{{ photo.title }}</td>
                <td>{{ photo.p_time }}</td>
                <td><a href="{% url 'photo:up_photoes' photo.id %}">修改</a> <a rel="6" href="{% url 'photo:del_photoes' photo.id %}">删除</a></td>
              </tr>
            {% endfor %}
            </tbody>
          </table>
        </div>
        <footer class="message_footer">
          <nav>
            <div class="btn-toolbar operation" role="toolbar">
              <div class="btn-group" role="group"> <a class="btn btn-default" onClick="select()">全选</a> <a class="btn btn-default" onClick="reverse()">反选</a> <a class="btn btn-default" onClick="noselect()">不选</a> </div>
              <div class="btn-group" role="group">
                <button type="submit" class="btn btn-default" data-toggle="tooltip" data-placement="bottom" title="删除全部选中" name="checkbox_delete">删除</button>
              </div>
            </div>
<ul class="pagination pagenav">
              <li>
              {% if photoes.has_previous %}
                  <a href="{% url 'photo:photoes' %}?page={{ photoes.previous_page_number }}">上一页</a>
              {% endif %}
              </li>
              <li>
              {% for i in photoes.paginator.page_range %}
              <a href="{% url 'photo:photoes' %}?page={{ i }}">{{ i }}</a>
              {% endfor %}
              </li>
              <li>
              {% if photoes.has_next %}
              <a href="{% url 'photo:photoes' %}?page={{ photoes.next_page_number }}">下一页</a>
              {% endif %}
              </li>
            </ul>
          </nav>
        </footer>
      </form>
    </div>
  </div>
</section>
{% endblock %}
{% block js2 %}
  {{ block.super }}
  <script src="/static/js/bootstrap.min.js"></script>
  <script src="/static/js/admin-scripts.js"></script>
  <script>
  //是否确认删除
  $(function(){
      $("#main table tbody tr td a").click(function(){
          var name = $(this);
          var id = name.attr("rel"); //对应id
          if (event.srcElement.outerText == "删除")
          {
              if(window.confirm("此操作不可逆，是否确认？"))
              {
                  $.ajax({
                      type: "POST",
                      url: "/Article/delete",
                      data: "id=" + id,
                      cache: false, //不缓存此页面
                      success: function (data) {
                          window.location.reload();
                      }
                  });
              };
          };
      });
  });
  </script>
{% endblock %}